// 生成 pdfmake 中文 vfs 模块：scripts/fonts/NotoSansSC-Regular.otf → src/utils/pdfTechPackVfs.js
// 运行：node scripts/gen_pdf_vfs.cjs
// 输出为 ES module（Vite 动态 import 使用），字体 base64 较大，由 Vite 自动拆为独立 chunk。
const fs = require('fs');
const path = require('path');

const fontPath = path.join(__dirname, 'fonts', 'NotoSansSC-Regular.otf');
const outPath = path.join(__dirname, '..', 'src', 'utils', 'pdfTechPackVfs.js');

if (!fs.existsSync(fontPath)) {
  console.error('字体文件不存在:', fontPath);
  process.exit(1);
}

const data = fs.readFileSync(fontPath).toString('base64');
const content =
`// AUTO-GENERATED by scripts/gen_pdf_vfs.cjs — 请勿手改；重新生成运行 node scripts/gen_pdf_vfs.cjs
// 数据源: scripts/fonts/NotoSansSC-Regular.otf（思源黑体 / Noto Sans SC，SIL OFL 开源）
export const pdfFontVfs = {
  "NotoSansSC-Regular.otf": { data: "${data}", encoding: "base64" }
};
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log('OK 生成', outPath, (content.length / 1024 / 1024).toFixed(2) + 'MB');
